version: '3.1'

networks:
  traefik:
    external: true
    name: traefik
  pg-net:
    external: true
  apk:
    name: apk-network

services:
  apk-backend:
    container_name: apk-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    labels:
      - traefik.http.routers.apk-backend.rule=${ROUTER_RULE}
      - traefik.http.routers.apk-backend.tls=true
      - traefik.http.routers.apk-backend.tls.certresolver=le
      - traefik.http.services.apk-backend.loadbalancer.server.port=${PORT}
    networks:
      - traefik
      - apk
      - pg-net
    environment:
      PORT: ${PORT}
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SYSTEMBOLAGET_SUBSCRIPTION_KEY: ${SYSTEMBOLAGET_SUBSCRIPTION_KEY}
